### ISSUE TITLE
model description fails

### ISSUE THREAD

**Issue by emschlegel** [fjebaker/SpectralFitting.jl#138]
![SpectralFitting_CrashA](https://github.com/user-attachments/assets/a70c0e2c-7f43-440e-8fc4-5f1449da55de)
![SpectralFitting_CrashB](https://github.com/user-attachments/assets/3f9abffd-070e-4d8c-bcf0-de9ada9aa469)

the screenshots should be read as A + B to cover the complete output.  I followed the walkthrough without issue to the line
       model=PhotoelectricAbsorption() * PowerLaw()
where things then failed.

I am running SpectralFitting on a Linux laptop using Julia 1.8.

**Comment by fjebaker** [comment]
Ah I think I see what's the issue here. `FunctionGeneration` doesn't exist in SpectralFitting anymore, which suggests you have an older version of SpectralFitting, likely because you are using Julia 1.8. As far as I know, there is no reason for us to require Julia >1.8 (which we currently do), so I can update the compat entries later and then hopefully that will resolve your problem (after an `update` in the package manager).

The alternative is that you can also update Julia to e.g. 1.10 or 1.11, but I will keep this issue open to remind me to check our Julia version compat.

Thanks for reporting!

**Comment by emschlegel** [comment]
hi --

   is there any limitation on running a particular version of julia?  i
used 'juliaup' to request version 1.10 and the response suggested
it was up and running.   but when i started julia, i was back at 1.8.

     -- ems

Eric M. Schlegel, Ph.D.   Vaughan Family Professor, Physics & Astronomy
Astrophysicist                               The University of Texas at San Antonio
Voice:  Real:  210.458.6425      One UTSA Circle, San Antonio, TX 78249
    virtual:  eric dot schlegel at utsa dot edu







________________________________________
From: Fergus Baker ***@***.***>
Sent: Monday, October 28, 2024 1:36 PM
To: fjebaker/SpectralFitting.jl
Cc: Eric Schlegel; Author
Subject: [EXTERNAL] Re: [fjebaker/SpectralFitting.jl] model description fails (Issue #138)

  **EXTERNAL EMAIL**
  This email originated outside of The University of Texas at San Antonio.
  Please exercise caution when clicking on links or opening attachments.



Ah I think I see what's the issue here. FunctionGeneration doesn't exist in SpectralFitting anymore, which suggests you have an older version of SpectralFitting, likely because you are using Julia 1.8. As far as I know, there is no reason for us to require Julia >1.8 (which we currently do), so I can update the compat entries later and then hopefully that will resolve your problem (after an update in the package manager).

The alternative is that you can also update Julia to e.g. 1.10 or 1.11, but I will keep this issue open to remind me to check our Julia version compat.

Thanks for reporting!

**Comment by fjebaker** [comment]
Someone in our office hit the same bug, and kindly let me look through their machine. Really I should have just grepped in the code-base: somehow, a reference to `FunctionGeneration` was still being used to write an error message to the user. SpectralFitting was trying to tell you the data for `PhotoelectricAbsorption` hadn't been downloaded, but was using a removed piece of code to generate the message.

Fixed in https://github.com/fjebaker/SpectralFitting.jl/commit/acffd5ee71d65db7711d56718a1b6b3fbee47e46
